server:
  port: 8011

email:
  subject: One time password

code:
  length: 10
  life.time: 180

spring:
  jpa:
    properties:
      hibernate:
        generate_statistics: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: #need to create
    password: #need to create
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
  data:
    jpa:
      repositories:
        bootstrap-mode: default

logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace
